import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'de' | 'fr' | 'en';


export const translations = {
  de: {
    nav_home:       'Home',
    nav_services:   'Leistungen',
    nav_about:      'Über uns',
    nav_references: 'Referenzen',
    nav_contact:    'Kontakt',
    nav_cta:        'Termin buchen',

    hero_eyebrow:   'Reinigungsdienst Bern',
    hero_h1a:       'Hinter jedem',
    hero_h1b:       'Glanz,',
    hero_h1c:       'echte',
    hero_h1d:       'Schweizer Sorgfalt.',
    hero_sub:       'Wir reinigen Wohnungen, Büros und Geschäftsräume in Bern und Umgebung — mit eigenem Team, ökologischen Mitteln und der Sorgfalt, die man Tag für Tag wirklich sieht.',
    hero_cta:       'Termin buchen',
    hero_badge1:    '★ 4.9 Google',
    hero_badge2:    'ISO 14001',
    hero_badge3:    '500+ Kunden',

    trust_label:    'Vertrauen durch:',

    stats_eyebrow:  'In Zahlen',
    stats_1_num:    '500',
    stats_1_suf:    '+',
    stats_1_label:  'Zufriedene Kunden',
    stats_2_num:    '8',
    stats_2_suf:    '',
    stats_2_label:  'Jahre Erfahrung',
    stats_3_num:    '98',
    stats_3_suf:    '%',
    stats_3_label:  'Weiterempfehlungsrate',
    stats_4_num:    '3',
    stats_4_suf:    '',
    stats_4_label:  'Städte in der Schweiz',

    pullquote:      '"Sauberkeit ist nicht ein Zustand — es ist eine Haltung."',
    pullquote_attr: '— Putzen®, seit 2016 · Bern',

    about_eyebrow:  'Die Putzen Philosophie',
    about_h2a:      'Klarheit entsteht durch',
    about_h2b:      'organisierte Räume.',
    about_text:     'Mit Schweizer Präzision sehen wir Reinigung nicht als Pflicht, sondern als Wiederherstellung von Harmonie. Jede Oberfläche wird mit absoluter Detailgenauigkeit behandelt, sodass Ihr Zuhause oder Arbeitsplatz zu einem echten Rückzugsort wird.',
    about_cta:      'Unser Prozess kennenlernen',

    services_eyebrow: 'Was wir bieten',
    services_h2a:   'Spezialisierte',
    services_h2b:   'Leistungen.',
    services_sub:   'Massgeschneiderte Reinigungskonzepte, entwickelt für die individuellen Ansprüche unterschiedlicher Umgebungen.',

    process_eyebrow: 'Unser Vorgehen',
    process_h2a:    'Die Methode',
    process_h2b:    'hinter der Klarheit.',
    process_sub:    'Ein systematischer Ansatz in der Reinigung, basierend auf Schweizer Präzision und tiefem Wissen über Materialien.',

    pricing_eyebrow: 'Transparente Preise',
    pricing_h2a:    'Das richtige Paket',
    pricing_h2b:    'für Sie.',
    pricing_sub:    'Klare Konditionen ohne versteckte Kosten. Wählen Sie das Paket, das zu Ihren Bedürfnissen passt.',

    calc_eyebrow:   'Preisrechner',
    calc_h2a:       'Ihr persönliches',
    calc_h2b:       'Angebot.',
    calc_sub:       'Konfigurieren Sie Ihren Reinigungsauftrag und erhalten Sie sofort eine Schätzung.',
    calc_type:      'Raumtyp',
    calc_area:      'Fläche (m²)',
    calc_freq:      'Häufigkeit',
    calc_label:     'Geschätzte Kosten',
    calc_incl:      'inkl. Reinigungsmittel · Geräte · Anfahrt',
    calc_cta:       'Angebot anfordern',

    team_eyebrow:   'Das Team',
    team_h2a:       'Hinter jedem Glanz',
    team_h2b:       'stehen Menschen.',
    team_sub:       'Unser erfahrenes Team behandelt Ihre Räume mit Respekt, Diskretion und höchster Sorgfalt.',

    refs_eyebrow:   'Kundenstimmen',
    refs_h2a:       'Vertrauen durch',
    refs_h2b:       'Qualität.',
    refs_sub:       'Was unsere Kunden in Bern und Umgebung über unsere Arbeit sagen.',

    faq_eyebrow:    'FAQ',
    faq_h2a:        'Häufige',
    faq_h2b:        'Fragen.',
    faq_sub:        'Alles, was Sie über unsere Arbeitsweise, Konditionen und Standards wissen müssen.',

    cta_h2a:        'Bereit für',
    cta_h2b:        'makellose Räume?',
    cta_text:       'Unsere Preise sind so individuell wie Ihre Räume. Für ein verbindliches Angebot kontaktieren Sie uns gerne per E-Mail, WhatsApp oder buchen Sie direkt einen Besichtigungstermin.',
    cta_wa:         'WhatsApp',
    cta_email:      'E-Mail',
    cta_book:       'Termin buchen',

    contact_eyebrow: 'Kontakt',
    contact_h2a:    'Schreiben Sie',
    contact_h2b:    'uns an.',
    contact_sub:    'Wir melden uns innerhalb von 24 Stunden. Für dringende Anfragen sind wir auch per WhatsApp erreichbar.',
    contact_submit:  'Nachricht senden',
    contact_sending: 'Wird gesendet…',
    contact_sent_h:  'Vielen Dank!',
    contact_sent_p:  'Wir haben Ihre Nachricht erhalten und melden uns innerhalb von 24 Stunden.',
    contact_error:   'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',

    pricing_cta:    'Anfragen',
    footer_dialogue_h:  'Starten Sie den',
    footer_dialogue_em: 'Dialog.',
    map_eyebrow:    'Standort',
    map_h2a:        'Wir sind in',
    map_h2b:        'Bern & Umgebung.',
    ba_eyebrow:     'Vorher & Nachher',
    ba_h2a:         'Der Unterschied,',
    ba_h2b:         'den man sieht.',
    ba_sub:         'Schieben Sie den Regler und erleben Sie die Transformation aus erster Hand.',
    ba_hint:        'Regler ziehen zum Vergleichen',
    cookie_label:   'Datenschutz',
    cookie_text:    'Wir verwenden Cookies, um Ihnen die bestmögliche Erfahrung auf unserer Website zu bieten.',
    cookie_link:    'Datenschutzerklärung',
    cookie_accept:  'Akzeptieren',
    cookie_decline: 'Ablehnen',
    footer_tagline: 'Der Standard für Sauberkeit in Bern und Umgebung.',
    footer_copy:    '© 2026 Putzen® Bern.',
    footer_privacy: 'Datenschutz',
    footer_imprint: 'Impressum',
  },
  fr: {
    nav_home:       'Accueil',
    nav_services:   'Services',
    nav_about:      'À propos',
    nav_references: 'Références',
    nav_contact:    'Contact',
    nav_cta:        'Prendre RDV',

    hero_eyebrow:   'Service de nettoyage Berne',
    hero_h1a:       'Derrière chaque',
    hero_h1b:       'éclat,',
    hero_h1c:       'un vrai soin',
    hero_h1d:       'suisse.',
    hero_sub:       'Nous nettoyons appartements, bureaux et commerces à Berne et alentours — avec notre propre équipe, des produits écologiques et un soin visible au quotidien.',
    hero_cta:       'Prendre rendez-vous',
    hero_badge1:    '★ 4.9 Google',
    hero_badge2:    'ISO 14001',
    hero_badge3:    '500+ clients',

    trust_label:    'Certifié par:',

    stats_eyebrow:  'En chiffres',
    stats_1_num:    '500',
    stats_1_suf:    '+',
    stats_1_label:  'Clients satisfaits',
    stats_2_num:    '8',
    stats_2_suf:    '',
    stats_2_label:  "Années d'expérience",
    stats_3_num:    '98',
    stats_3_suf:    '%',
    stats_3_label:  'Taux de recommandation',
    stats_4_num:    '3',
    stats_4_suf:    '',
    stats_4_label:  'Villes en Suisse',

    pullquote:      '"La propreté n\'est pas un état — c\'est une attitude."',
    pullquote_attr: '— Putzen®, depuis 2016 · Berne',

    about_eyebrow:  'La philosophie Putzen',
    about_h2a:      'La clarté naît d\'espaces',
    about_h2b:      'bien organisés.',
    about_text:     'Avec la précision suisse, nous voyons le nettoyage non comme une obligation, mais comme le rétablissement de l\'harmonie. Chaque surface est traitée avec une attention absolue aux détails.',
    about_cta:      'Notre processus',

    services_eyebrow: 'Ce que nous offrons',
    services_h2a:   'Services',
    services_h2b:   'spécialisés.',
    services_sub:   'Concepts de nettoyage sur mesure, conçus pour les exigences individuelles de différents environnements.',

    process_eyebrow: 'Notre approche',
    process_h2a:    'La méthode',
    process_h2b:    'derrière la clarté.',
    process_sub:    'Une approche systématique basée sur la précision suisse et une connaissance approfondie des matériaux.',

    pricing_eyebrow: 'Tarifs transparents',
    pricing_h2a:    'Le bon forfait',
    pricing_h2b:    'pour vous.',
    pricing_sub:    'Conditions claires sans frais cachés.',

    calc_eyebrow:   'Calculateur de prix',
    calc_h2a:       'Votre devis',
    calc_h2b:       'personnalisé.',
    calc_sub:       'Configurez votre mission et obtenez une estimation immédiate.',
    calc_type:      'Type de local',
    calc_area:      'Surface (m²)',
    calc_freq:      'Fréquence',
    calc_label:     'Coût estimé',
    calc_incl:      'incl. produits · matériel · déplacement',
    calc_cta:       'Demander un devis',

    team_eyebrow:   "L'équipe",
    team_h2a:       'Derrière chaque éclat',
    team_h2b:       'il y a des gens.',
    team_sub:       'Notre équipe expérimentée traite vos espaces avec respect et discrétion.',

    refs_eyebrow:   'Témoignages',
    refs_h2a:       'Confiance par la',
    refs_h2b:       'qualité.',
    refs_sub:       "Ce que nos clients à Berne disent de notre travail.",

    faq_eyebrow:    'FAQ',
    faq_h2a:        'Questions',
    faq_h2b:        'fréquentes.',
    faq_sub:        'Tout ce que vous devez savoir sur notre façon de travailler.',

    cta_h2a:        'Prêt pour des espaces',
    cta_h2b:        'impeccables?',
    cta_text:       'Nos prix sont aussi individuels que vos espaces. Contactez-nous par e-mail, WhatsApp ou prenez directement rendez-vous.',
    cta_wa:         'WhatsApp',
    cta_email:      'E-Mail',
    cta_book:       'Prendre RDV',

    contact_eyebrow: 'Contact',
    contact_h2a:    'Écrivez-nous',
    contact_h2b:    'maintenant.',
    contact_sub:    'Nous répondons dans les 24 heures. Pour les demandes urgentes, contactez-nous par WhatsApp.',
    contact_submit:  'Envoyer le message',
    contact_sending: 'Envoi en cours…',
    contact_sent_h:  'Merci beaucoup !',
    contact_sent_p:  'Nous avons reçu votre message et vous répondrons dans les 24 heures.',
    contact_error:   'Quelque chose a mal tourné. Veuillez réessayer.',

    pricing_cta:    'Demander',
    footer_dialogue_h:  'Commencez le',
    footer_dialogue_em: 'dialogue.',
    map_eyebrow:    'Localisation',
    map_h2a:        'Nous sommes à',
    map_h2b:        'Berne & environs.',
    ba_eyebrow:     'Avant & Après',
    ba_h2a:         'La différence',
    ba_h2b:         'qui se voit.',
    ba_sub:         'Faites glisser le curseur pour voir la transformation par vous-même.',
    ba_hint:        'Glisser pour comparer',
    cookie_label:   'Confidentialité',
    cookie_text:    'Nous utilisons des cookies pour vous offrir la meilleure expérience possible sur notre site.',
    cookie_link:    'Politique de confidentialité',
    cookie_accept:  'Accepter',
    cookie_decline: 'Refuser',
    footer_tagline: 'Le standard de propreté à Berne et alentours.',
    footer_copy:    '© 2026 Putzen® Berne.',
    footer_privacy: 'Confidentialité',
    footer_imprint: 'Mentions légales',
  },
  en: {
    nav_home:       'Home',
    nav_services:   'Services',
    nav_about:      'About',
    nav_references: 'References',
    nav_contact:    'Contact',
    nav_cta:        'Book now',

    hero_eyebrow:   'Cleaning Service Bern',
    hero_h1a:       'Behind every',
    hero_h1b:       'shine,',
    hero_h1c:       'real Swiss',
    hero_h1d:       'craftsmanship.',
    hero_sub:       'We clean apartments, offices and commercial spaces in Bern and surroundings — with our own team, ecological products and the care you actually see every day.',
    hero_cta:       'Book appointment',
    hero_badge1:    '★ 4.9 Google',
    hero_badge2:    'ISO 14001',
    hero_badge3:    '500+ clients',

    trust_label:    'Trusted by:',

    stats_eyebrow:  'By the numbers',
    stats_1_num:    '500',
    stats_1_suf:    '+',
    stats_1_label:  'Happy clients',
    stats_2_num:    '8',
    stats_2_suf:    '',
    stats_2_label:  'Years of experience',
    stats_3_num:    '98',
    stats_3_suf:    '%',
    stats_3_label:  'Recommendation rate',
    stats_4_num:    '3',
    stats_4_suf:    '',
    stats_4_label:  'Swiss cities',

    pullquote:      '"Cleanliness is not a state — it is an attitude."',
    pullquote_attr: '— Putzen®, since 2016 · Bern',

    about_eyebrow:  'The Putzen Philosophy',
    about_h2a:      'Clarity comes from',
    about_h2b:      'organised spaces.',
    about_text:     'With Swiss precision, we see cleaning not as a chore but as the restoration of harmony. Every surface is treated with absolute attention to detail, so your home or workplace becomes a true sanctuary.',
    about_cta:      'See our process',

    services_eyebrow: 'What we offer',
    services_h2a:   'Specialised',
    services_h2b:   'services.',
    services_sub:   'Tailored cleaning concepts designed for the individual needs of different environments.',

    process_eyebrow: 'Our approach',
    process_h2a:    'The method',
    process_h2b:    'behind clarity.',
    process_sub:    'A systematic approach to cleaning, grounded in Swiss precision and deep knowledge of materials.',

    pricing_eyebrow: 'Transparent pricing',
    pricing_h2a:    'The right package',
    pricing_h2b:    'for you.',
    pricing_sub:    'Clear terms with no hidden costs. Choose the package that fits your needs.',

    calc_eyebrow:   'Price calculator',
    calc_h2a:       'Your personal',
    calc_h2b:       'estimate.',
    calc_sub:       'Configure your cleaning job and get an instant price estimate.',
    calc_type:      'Space type',
    calc_area:      'Area (m²)',
    calc_freq:      'Frequency',
    calc_label:     'Estimated cost',
    calc_incl:      'incl. products · equipment · travel',
    calc_cta:       'Request quote',

    team_eyebrow:   'The team',
    team_h2a:       'Behind every shine',
    team_h2b:       'stand people.',
    team_sub:       'Our experienced team treats your spaces with respect, discretion and the utmost care.',

    refs_eyebrow:   'Client voices',
    refs_h2a:       'Trust through',
    refs_h2b:       'quality.',
    refs_sub:       'What our clients in Bern and surroundings say about our work.',

    faq_eyebrow:    'FAQ',
    faq_h2a:        'Frequently asked',
    faq_h2b:        'questions.',
    faq_sub:        'Everything you need to know about our process, pricing and standards.',

    cta_h2a:        'Ready for',
    cta_h2b:        'spotless spaces?',
    cta_text:       'Our prices are as individual as your spaces. Contact us by email, WhatsApp or book a site visit directly.',
    cta_wa:         'WhatsApp',
    cta_email:      'E-Mail',
    cta_book:       'Book now',

    contact_eyebrow: 'Contact',
    contact_h2a:    'Write',
    contact_h2b:    'to us.',
    contact_sub:    'We respond within 24 hours. For urgent enquiries, reach us via WhatsApp.',
    contact_submit:  'Send message',
    contact_sending: 'Sending…',
    contact_sent_h:  'Thank you!',
    contact_sent_p:  'We received your message and will get back to you within 24 hours.',
    contact_error:   'Something went wrong. Please try again.',

    pricing_cta:    'Enquire',
    footer_dialogue_h:  'Start the',
    footer_dialogue_em: 'dialogue.',
    map_eyebrow:    'Location',
    map_h2a:        'We serve',
    map_h2b:        'Bern & surroundings.',
    ba_eyebrow:     'Before & After',
    ba_h2a:         'The difference',
    ba_h2b:         'you can see.',
    ba_sub:         'Drag the slider to experience the transformation first-hand.',
    ba_hint:        'Drag to compare',
    cookie_label:   'Privacy',
    cookie_text:    'We use cookies to give you the best possible experience on our website.',
    cookie_link:    'Privacy policy',
    cookie_accept:  'Accept',
    cookie_decline: 'Decline',
    footer_tagline: 'The standard for cleanliness in Bern and surroundings.',
    footer_copy:    '© 2026 Putzen® Bern.',
    footer_privacy: 'Privacy',
    footer_imprint: 'Imprint',
  },
} as const;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (typeof translations)[Lang];
}

const LangContext = createContext<LangContextType>({
  lang: 'de',
  setLang: () => {},
  t: translations.de,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('de');
  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
